/*
 * Generated by XDoclet - Do not edit!
 */
package com.sample.service;

/**
 * Remote interface for CounterService.
 * @generated 
 */
public interface CounterService
   extends javax.ejb.EJBObject
{
   /**
    * <!-- begin-xdoclet-definition -->
    * @generated     */
   public int increment(  )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated     */
   public int decrement(  )
      throws java.rmi.RemoteException;

}
