/*
 * Generated by XDoclet - Do not edit!
 */
package com.sample.service;

/**
 * Home interface for CounterService.
 * @generated 
 */
public interface CounterServiceHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/CounterService";
   public static final String JNDI_NAME="ejb/CounterService";

   public com.sample.service.CounterService create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
