/*
 * Generated by XDoclet - Do not edit!
 */
package com.sample.service;

/**
 * Local interface for EchoService.
 * @generated 
 */
public interface EchoServiceLocal
   extends javax.ejb.EJBLocalObject
{

}
