/*
 * Generated by XDoclet - Do not edit!
 */
package com.sample.service;

/**
 * Session layer for EchoService.
 * @generated 
 */
public class EchoServiceSession
   extends com.sample.service.EchoServiceBean
   implements javax.ejb.SessionBean
{
   public void ejbActivate() 
   {

   }

   public void ejbPassivate() 
   {
   }

   public void setSessionContext(javax.ejb.SessionContext ctx) 
   {
   }

   public void unsetSessionContext() 
   {
   }

   public void ejbRemove() 
   {
   }

}
