/*
 * Generated by XDoclet - Do not edit!
 */
package com.sample.service;

/**
 * Remote interface for EchoService.
 * @generated 
 */
public interface EchoService
   extends javax.ejb.EJBObject
{
   /**
    * <!-- begin-xdoclet-definition -->
    * @generated     */
   public java.lang.String echo( java.lang.String message )
      throws java.rmi.RemoteException;

}
