/*
 * Generated by XDoclet - Do not edit!
 */
package com.sample.service;

/**
 * Home interface for EchoService.
 * @generated 
 */
public interface EchoServiceHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/EchoService";
   public static final String JNDI_NAME="ejb/EchoService";

   public com.sample.service.EchoService create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
